// Copy the latin/greek variable subsets of each candidate face into src/fonts,
// and emit a single fonts.css. Google's subset split gives us unicode-range
// loading for free, so the browser fetches Greek only when Greek is on the page.
import { readFileSync, writeFileSync, copyFileSync, mkdirSync } from "node:fs";

// EB Garamond was chosen over Literata, Alegreya and Source Serif 4 by setting
// a real post in all four; to compare again, add them back and rebuild.
const FAMILIES = [
  ["eb-garamond", "EB Garamond Variable"],
];
const KEEP = ["latin", "latin-ext", "greek", "greek-ext"];
const only = process.argv[2];               // optional: build just one family

mkdirSync("src/fonts", { recursive: true });
let css = "/* Self-hosted variable subsets. Generated by tools/fonts.mjs — do not edit. */\n";

for (const [pkg, family] of FAMILIES) {
  if (only && only !== pkg) continue;
  for (const sheet of ["wght.css", "wght-italic.css"]) {
    const src = readFileSync(`node_modules/@fontsource-variable/${pkg}/${sheet}`, "utf8");
    for (const block of src.split("@font-face").slice(1)) {
      const file = block.match(/files\/([^)]+\.woff2)/)?.[1];
      if (!file) continue;
      // subset name sits between the package name and the axis suffix
      const subset = file.slice(pkg.length + 1).replace(/-wght(-normal|-italic)?\.woff2$/, "");
      if (!KEEP.includes(subset)) continue;
      copyFileSync(`node_modules/@fontsource-variable/${pkg}/files/${file}`, `src/fonts/${file}`);
      css += "@font-face" + block.replace(/url\(\.\/files\//, "url(/fonts/").replace(/\n\s*\n/g, "\n") + "\n";
    }
  }
  // the OFL requires the licence to ship alongside the fonts
  copyFileSync(`node_modules/@fontsource-variable/${pkg}/LICENSE`, "src/fonts/LICENSE.txt");
  console.log(`${family}: subsets copied`);
}
writeFileSync("src/css/fonts.css", css);
console.log(`\nsrc/css/fonts.css written (${css.split("@font-face").length - 1} faces)`);
